Task Order 24 cleaned changes
SmarterApp/TDS_Student pull request #10
Opened 2017-01-12 17:34 UTC by rlevy12

This PR represents the cleaned-up and combined changes to Student with respect to Task Order 24. This is done to eliminate the noise caused by auto formatting in earlier versions of these changed files, which complicated comparing and merging.

2017-01-19 22:15 UTC, hbgwhite commented on student/src/main/java/tds/student/web/controls/dummy/ResourcesLink.java
> +				 * ScriptLink scriptLink = new ScriptLink();
Please do not check in commented code.

2017-01-19 22:17 UTC, hbgwhite commented on student/src/main/webapp/Projects/SBAC/Help/help_streamlined.html
> +<!--SECTION 1-->
Please do not check in commented code

2017-01-19 22:20 UTC, hbgwhite commented on student/src/main/webapp/Shared/CSS/Universal/shell.css
>  	overflow:hidden;
It appears that this file was formatted outside of the areas where actual changes were made. These formatting changes make it very difficult to tell what actually changed. Please re-submit this file without the formatting.

2017-01-19 22:23 UTC, hbgwhite commented on student/src/main/webapp/resources/sections/TTSCheck.xhtml
> +				<tds:NextStepWrapper id="sectionCheckSoundSpanishNextSteps"
Are there changes here or is this just formatting? Please submit a clearer diff.

2017-01-19 22:25 UTC, hbgwhite requested changes
There are some files in this pull request that appear to have been formatted independent of any changes. It's difficult to review these files. Please re-submit the changes without formatting.

There are some files that look as if code has been commented out in the commits and then checked in. If the code is no longer in use, please remove it.

2017-01-20 00:33 UTC, vkesharia commented on student/src/main/webapp/resources/sections/TTSCheck.xhtml
> +				<tds:NextStepWrapper id="sectionCheckSoundSpanishNextSteps"
This are actual code changes

2017-01-20 15:56 UTC, vkesharia commented on student/src/main/webapp/Shared/CSS/Universal/shell.css
>  	overflow:hidden;
Below commit is the actual code change
https://github.com/SmarterApp/TDS_Student/commit/7578c162c4a582e1d1d71b92e6763d57fcbfd9d0?diff=split

2017-01-20 16:02 UTC, vkesharia commented on student/src/main/java/tds/student/web/controls/dummy/ResourcesLink.java
> +				 * ScriptLink scriptLink = new ScriptLink();
Will will remove commented out code and commit

2017-01-20 16:02 UTC, vkesharia commented on student/src/main/webapp/Projects/SBAC/Help/help_streamlined.html
> +<!--SECTION 1-->
Will will remove commented out code and commit

2017-01-23 21:11 UTC, hbgwhite commented on student/src/main/webapp/Projects/SBAC/Help/help.html
> +          <td class="toolRight">Use the [<strong>Line Reader</strong>] button to highlight a line of text on the page. When you click this button, the first line of text on the page will be highlight
Please remove commented sections

2017-01-23 21:11 UTC, hbgwhite commented on student/src/main/webapp/Projects/SBAC/Help/help_esn.html
> +          <!--<tr>
Please remove commented sections

2017-01-23 21:19 UTC, vkesharia commented on student/src/main/webapp/Projects/SBAC/Help/help.html
> +          <td class="toolRight">Use the [<strong>Line Reader</strong>] button to highlight a line of text on the page. When you click this button, the first line of text on the page will be highlight
https://github.com/SmarterApp/TDS_Student/commit/534f9518227418dacff23eea853aff4175c39d14

2017-01-23 21:19 UTC, vkesharia commented on student/src/main/webapp/Projects/SBAC/Help/help_esn.html
> +          <!--<tr>
https://github.com/SmarterApp/TDS_Student/commit/534f9518227418dacff23eea853aff4175c39d14

2017-03-14 06:01 UTC, jtreuting commented
Completed as part of https://github.com/SmarterApp/TDS_Student/pull/34

2017-03-14 06:01 UTC, closed without merging