/denyApproval and /setStatus implementations
SmarterApp/TDS_Student pull request #18
Opened 2017-02-15 21:47 UTC by burzum619

This PR includes implementations of the /setStatus and /denyApproval integration with the performance exam service. The legacy implementations of these methods are found in OpportunityService.java. 

There are a few minor changes to other repos that this PR will depend on:

TDS_Common - NoContentResponseResource.java 
  - Added private empty constructor for jackson deserialization
TDS_Exam - ExamStatusCode and StatusTransitionValidator
  - Made status transition and state map lookups to be case-insensitive.

2017-02-15 21:49 UTC, burzum619 commented on student/src/main/java/tds/student/sql/repository/RemoteExamRepository.java
> -          builder.build().encode().toUri(),
My apologies for these accidental formatting commits - but on that note, are we using 2-space indents or 4-space indents for new lines in legacy TDS_Student?

2017-02-15 21:58 UTC, millerts requested changes
Couple small requests.

2017-02-15 21:58 UTC, millerts commented on student/src/main/java/tds/student/services/remote/RemoteOpportunityService.java
> +    /* Conditional on line [257] */
Can you add the class name?  I understand it is in the legacy opportunity service but the comment will make more sense for people that aren't in the know.

2017-02-15 21:58 UTC, millerts commented on student/src/main/java/tds/student/services/remote/RemoteOpportunityService.java
> +    /* Conditional on line [257] */
Same for anywhere we reference line numbers.

2017-02-15 21:58 UTC, millerts commented on student/src/main/java/tds/student/services/remote/RemoteOpportunityService.java
> +      isApproved = true;
Can we flip this conditional so it is:

```
if (!maybeError.isPresent()) {
  return true;
}

Validation error = maybeError.get();
//rest of logic

return false; // if not excpetion thrown
```

2017-02-15 21:58 UTC, millerts commented on student/src/main/java/tds/student/sql/repository/RemoteExamRepository.java
> +        builder.build().encode().toUri(),
I must have had the performance code style setting when I changed this code.

2017-02-15 21:58 UTC, millerts commented on student/src/main/java/tds/student/sql/repository/RemoteExamRepository.java
> +      .queryParam("status", status)
This is nothing to do with your code but it seems odd to me that we are using query parameters rather than putting a body object with these values.  Query params to me are normally used to impact the query being done.  Like search parameters.

2017-02-15 21:58 UTC, millerts commented on student/src/main/java/tds/student/sql/repository/RemoteExamRepository.java
> +  private NoContentResponseResource handleErrorResponseNoContent(String body) throws ReturnStatusException {
Can you add a unit test for that hits this block?

2017-02-15 21:59 UTC, millerts commented on student/src/main/java/tds/student/sql/repository/RemoteExamRepository.java
> -          builder.build().encode().toUri(),
2 space because that is what they use.  I imagine I didn't have the write code style in my IDE and missed it.

2017-02-16 00:05 UTC, burzum619 commented on student/src/main/java/tds/student/sql/repository/RemoteExamRepository.java
> +      .queryParam("status", status)
Agreed. we can chat about it in the parking lot tomorrow.

2017-02-16 00:05 UTC, merged