Feature/event logging
SmarterApp/TDS_Student pull request #30
Opened 2017-03-08 18:23 UTC by mtrupkin

2017-03-08 20:36 UTC, wtritch commented on student/pom.xml
> +		<sb11-shared-code.version>3.0.1-SNAPSHOT</sb11-shared-code.version>
Please release sb11-shared-code and bump to a released version before merging. =)

2017-03-08 20:37 UTC, wtritch commented on student/src/main/java/tds/student/web/handlers/TestShellHandler.java
> +    EventLogger.info(StudentEventLogger.APP, StudentEventLogger.StudentLogEvent.PAUSE_EXAM, Checkpoint.ENTER.name(),
Should this be StudentEventLogger.info ?

2017-03-08 20:38 UTC, wtritch commented on student/src/main/java/tds/student/web/handlers/TestShellHandler.java
> +      request.getSession().getId(), null, null);
maybe pull request.getSession().getId() into a sessionId variable?

2017-03-08 20:40 UTC, wtritch requested changes
Just requesting a release of sb11-shared-code.

2017-03-10 17:44 UTC, mtrupkin commented
Researching alternate approach to event logging in the feature/event-interceptor branch.
Looking to inspect the http request/response in order to determine the event type and event specific data.

2017-03-10 17:44 UTC, closed without merging